# Generated by Django 5.2.3 on 2025-07-03 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0003_location_meetup_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="meetup",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="meetups.location"
            ),
        ),
        migrations.AddField(
            model_name="meetup",
            name="participant",
            field=models.ManyToManyField(blank=True, to="meetups.participant"),
        ),
    ]
