# Generated by Django 5.2.3 on 2025-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0004_participant_alter_meetup_location_meetup_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(default="1980-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="no_email@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
